### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rikkimax** [WebFreak001/nbtD#1]
May I ask why GPL and not something more liberal like Boost or MIT?
As D community prefers Boost.

Btw I'm planning on working on a Minecraft mod in D in a couple weeks. It'll be live streamed.
Right now I'm working on making Java->D/D->Java play nicely via JNI.

**Comment by WebFreak001** [comment]
Well I usually use GPL because other software I like uses it and I have no idea where the difference is except what http://choosealicense.com/ says.

Actually now that I think about it, I think im gonna choose a public domain license instead.

**Comment by rikkimax** [comment]
Licenses like GPL restrict other developers on how to use it. Essentially forcing them to contribute back and only for use with other opensource software. Aka no use for proprietary uses.
It's well regarded as bad form these days. As it spreads awfully. It's one of the reasons people do not like GCC.

Public domain pretty much means you lose full control over it. I highly recommend a liberal license like MIT, BSD or Boost. They give you control over it while keeping yourself safe. But it also means everyone can do pretty much anything with it. Except claim to be you.

**Comment by WebFreak001** [comment]
Yeah I know that I will lose full control over it but it really wasn't much work and I want people to do whatever they want with it
